#' RobustFlow: Robustness and Drift Auditing for Longitudinal Decision Systems
#'
#' @description
#' RobustFlow provides a principled toolkit for researchers who study how
#' decisions or outcomes evolve across repeated observations of the same
#' individuals. It is designed around three methodological contributions:
#'
#' \describe{
#'   \item{Drift Intensity Index (DII)}{Quantifies structural instability in
#'     the transition system between consecutive time periods using the
#'     Frobenius norm of adjacent period-specific transition matrix differences.
#'     See [compute_drift()].}
#'   \item{Bias Amplification Index (BAI)}{Measures whether group disparities
#'     widen or narrow over time. See [compute_bai()].}
#'   \item{Temporal Fragility Index (TFI)}{Estimates the minimum amount of
#'     hidden bias required to nullify a longitudinal trend conclusion.
#'     See [compute_tfi_simple()].}
#' }
#'
#' An interactive Shiny application ([run_app()]) provides a seven-tab
#' workflow covering data upload, path construction, drift and disparity
#' analysis, robustness auditing, and reproducible report export.
#'
#' @references
#' Hait, S. (2025). \emph{RobustFlow: Robustness and drift auditing for
#' longitudinal decision systems}. R package version 0.1.0.
#' \url{https://github.com/subirhait/RobustFlow}
#'
#' @keywords internal
"_PACKAGE"

# -----------------------------------------------------------------------
# Package-level importFrom declarations
# These drive the NAMESPACE generated by devtools::document().
# -----------------------------------------------------------------------

# golem - only import what is actually exported by golem
#' @importFrom golem with_golem_options add_resource_path
NULL

#' @importFrom shiny fluidPage sidebarLayout sidebarPanel mainPanel
#'   tabsetPanel tabPanel titlePanel br hr div span h2 h4 h5 h6 p icon
#'   fileInput selectInput numericInput checkboxInput actionButton
#'   downloadButton uiOutput textOutput column wellPanel reactive
#'   reactiveVal eventReactive observeEvent renderUI renderText req
#'   validate need isolate downloadHandler shinyApp
NULL

#' @importFrom htmltools tagList tags
NULL

#' @importFrom bslib bs_theme
NULL

#' @importFrom DT datatable renderDT DTOutput
NULL

#' @importFrom plotly ggplotly renderPlotly plotlyOutput
NULL

#' @importFrom ggplot2 ggplot aes geom_line geom_point geom_col
#'   geom_hline coord_flip scale_y_continuous labs theme_minimal annotate
NULL

#' @importFrom scales percent_format
NULL

#' @importFrom rmarkdown render
NULL

#' @importFrom stats aggregate lm coef sd
NULL

#' @importFrom utils head tail read.csv write.csv zip packageVersion
NULL

#' @importFrom tools file_ext
NULL
